### ISSUE TITLE
Connect Core CI with Distributable's Repo

### ISSUE THREAD

**Issue by shaggyyy2002** [metacall/core#505]
## 🚀 Feature

Consistent CI across multiple repositories in order to provide continuous delivery of MetaCall binaries with report of errors for when some distributable fails on a version of MetaCall Core.

### Is your feature request related to a problem? 
Earlier when a new tag was being pushed it would only trigger the core repo CI to build binaries. Adding a new CI in which when a new tag is pushed and repo is built successfully then it will trigger the distributable repo's (windows/linux/macos) to build new binaries with newer version/tags.

### Describe the solution you'd like
My current solution uses [github.com/peter-evans/repository-dispatch@v2](https://github.com/peter-evans/repository-dispatch).  Where we can use this Github Action to trigger in remote repo 

Dispatch to multiple repositories. You can dispatch to multiple repositories by using a [matrix strategy](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix). 
In the following example, after the build job succeeds, an event is dispatched to three different repositories.

```yml
    strategy:
      matrix:
        repo: ['metacall/distributable-windows', 'metacall/distributable-linux', 'metacall/distributable-macos']

```

**Comment by shaggyyy2002** [comment]
using this under the release.yml file so that dispatch runs when the release.yml file is build as mentioned `needs: build`. if created a separate file for this it may sometimes run first or last as its picked or we would need to use if else statements, this is more easy.    
 
```yml
name: Release

on:
  push:
    tags:
    - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GHR_VERSION: 0.12.0
  IMAGE_NAME: index.docker.io/metacall/core
  IMAGE_REGISTRY: index.docker.io
  ARTIFACTS_PATH: ./build-artifacts
  # GITHUB_TOKEN      - From default secrets
  # GITHUB_REPOSITORY - Default variable

jobs:
  build:
    name: Build the core
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
.
.
.
. [continued in core]
.
.
 dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['company/repo1', 'company/repo2', 'company/repo3']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: test-trigger   
   ```
This is what it would look like:  

<img width="1440" alt="Screenshot 2024-06-04 at 10 12 29 PM" src="https://github.com/metacall/core/assets/90847875/1e8f6232-b8ff-4650-b647-ea61aa05b49f">

**Comment by shaggyyy2002** [comment]
some minor changes: we are using `client-payload: '{"ref": "${{ github.ref }}"}'` 
the earlier `ref: ${{ github.ref }}` is deprecated for v3 dispatch.
More info : https://github.com/peter-evans/repository-dispatch

**Comment by shaggyyy2002** [comment]
On the core repo its done. 
1. A tag when pushed and the testCI is passed (in core repo) only then it will trigger the remote distributable repo (linux, window, mac) to make the dist repo accept the req. 
(image from core repo LinuxCI)
<img width="1440" alt="Screenshot 2024-06-21 at 2 28 19 AM" src="https://github.com/metacall/core/assets/90847875/bc8ab1bd-2826-430b-8639-d637a56e61be">
2. Now we need to change the CI in the dist repo so that when the trigger reaches it will start the CI process of that repo

changes needed on the dist repo's
```yml
name: "MetaCall Distributable Release"

on:
  repository_dispatch:
    types: [test-trigger]
```

(Image from linux-dist repo)
<img width="1427" alt="Screenshot 2024-06-21 at 2 31 07 AM" src="https://github.com/metacall/core/assets/90847875/f21bf274-78f3-461c-9f97-36744312b768">
